import { TimelineBuilder, type Timeline } from '../engine/timeline'
import type { Director } from './director'
import { chisel, lantern, overtake, snake, spiral, vee } from './formations'

/**
 * Stage 1 "The Shattered Ring", authored as one engine Timeline. The Director (the scene) exposes
 * only verbs; every beat of pacing lives here as data, so re-pacing never touches gameplay code.
 */
export function buildRingStage(): Timeline<Director> {
  const b = new TimelineBuilder<Director>()
  b.label('intro')
    .call(d => {
      d.setTheme('ring')
      d.setMusic('cruise')
      d.setRail('cruise')
      d.letterbox(true)
      d.cinematic('launch')
      d.banner('stage.title', 'stage.sub', 'phase')
    })
    .wait(3.4)
    .call(d => {
      d.letterbox(false)
      d.cinematic('none')
      if (d.tutorial) d.hint('hint.move')
    })
    .wait(1.2)

  b.label('warmup')
    .use(snake(-1))
    .wait(2.2)
    .call(d => d.tutorial && d.hint('hint.fire'))
    .use(snake(1))
    .wait(3.2)
    .use(vee(0, 2, 'aimed'))
    .wait(3.6)
    .call(d => d.tutorial && d.hint('hint.roll'))
    .use(vee(-8, -1, 'aimed'))
    .wait(0.8)
    .use(vee(8, 3, 'aimed'))
    .gate(d => d.hostiles() === 0, 7)
    .call(d => {
      d.hint(null)
      d.tutorialFinished()
    })
    .wait(0.8)

  b.label('wave1')
    .call(d => {
      d.banner('wave1.title', 'wave1.sub', 'phase')
      d.setMusic('battle')
    })
    .wait(1.6)
    .use(snake(-1, 'aimed', 7, 5))
    .wait(1.0)
    .use(snake(1, 'aimed', 7, -1))
    .wait(2.6)
    .call(chisel(-7, 3, 'fan3'))
    .call(chisel(7, 3, 'fan3'))
    .wait(3.2)
    .use(spiral('aimed'))
    .wait(3.0)
    .call(d => d.hint(null))
    .use(overtake('aimed', 8))
    .wait(3.0)
    .call(chisel(-9, -2, 'burst'))
    .call(chisel(0, 5, 'burst', 4.5, true))
    .call(chisel(9, -2, 'burst'))
    .wait(3.4)
    .call(lantern(0, 1.5))
    .wait(1.4)
    .use(vee(-12, 5))
    .wait(1.2)
    .use(vee(12, -3))
    .gate(d => d.hostiles() === 0, 14)
    .wait(1.0)

  b.label('storm')
    .call(d => {
      d.banner('storm.title', 'storm.sub', 'warning')
      d.setRail('boost')
      d.setMusic('storm')
    })
    .wait(1.2)
  const rocksStart = b.time
  b.every(0.32, 56, (d, i) => {
      d.rock(i % 9 === 4, i % 6 === 0 ? 'player' : 'random')
      if (i % 2) d.rock(false)
      if (i % 11 === 5) d.mine()
    })
  const rocksEnd = b.time
  // Layer two harmless formations over the rock storm for bonus points.
  b.at(rocksStart + 5)
    .use(snake(-1, 'none', 6, 6))
    .wait(3.5)
    .use(snake(1, 'none', 6, -3))
    .at(rocksEnd + 1.5)
    .call(d => d.setRail('cruise'))
    .wait(2.2)

  b.label('wave2')
    .call(d => {
      d.banner('wave2.title', 'wave2.sub', 'phase')
      d.setMusic('battle')
    })
    .wait(1.6)
    .call(chisel(-8, 4, 'ring', 5))
    .call(chisel(8, 4, 'ring', 5))
    .call(chisel(0, -3, 'fan5', 5, true))
    .wait(3.8)
    .use(overtake('burst', 8))
    .wait(3.4)
    .call(lantern(-9, 3, 'spiral', 7))
    .call(lantern(9, 3, 'ring', 7))
    .wait(2.5)
    .use(snake(-1, 'aimed', 6, -4))
    .wait(4.5)
    .use(vee(0, 8, 'fan3'))
    .wait(0.6)
    .use(vee(0, -6, 'aimed'))
    .wait(3)
    .call(chisel(-6, 0, 'fan5', 4))
    .call(chisel(6, 0, 'fan5', 4, true))
    .every(0.9, 5, d => d.rock(false, 'random'))
    .use(spiral('burst'))
    .wait(2.5)
    .call(lantern(0, 2, 'spiral', 6))
    .use(snake(1, 'aimed', 6, 7))
    .gate(d => d.hostiles() === 0, 16)
    .wait(1.2)

  b.label('boss')
    .call(d => {
      d.checkpointHere('boss')
      d.setRail('boss')
      d.setMusic('none')
      d.warning(true)
      d.banner('warning.title', 'warning.sub', 'warning')
    })
    .wait(3.6)
    .call(d => {
      d.warning(false)
      d.letterbox(true)
      d.cinematic('boss')
      d.startBoss()
      d.setMusic('boss')
    })
    .wait(5.2)
    .call(d => {
      d.letterbox(false)
      d.cinematic('none')
    })
    .gate(d => d.bossDefeated())
    .label('clear')
  return b.build()
}
