// Provisions a headless Chromium for `pnpm smoke` on machines where Playwright's browser download
// is blocked (this sandbox, some CI images). It fetches the AWS-Lambda Chromium bundles from npm,
// brotli-decompresses them and assembles a runnable browser directory next to the repo, then prints
// the environment `scripts/smoke.mjs` understands.
//
//   node scripts/headless-browser.mjs [--dir .chromium] [--version 110.0.1]
//
// Why this exact mix: the trimmed Lambda build ships no GL driver, so the browser needs SwiftShader
// GLES libraries from `chrome-aws-lambda@10.1.0` plus the NSS/freebl runtime from a current
// `@sparticuz/chromium`, and it is launched with `--use-gl=egl`. The directory is generated, big
// (~60 MB) and never committed.
import { execFileSync } from 'node:child_process'
import { brotliDecompressSync } from 'node:zlib'
import { chmodSync, copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

const dir = resolve(arg('dir', '.chromium'))
const version = arg('version', '110.0.1')
const work = join(dir, '.packages')
const npm = spec => execFileSync('npm', ['i', '--silent', '--no-audit', '--no-fund', '--prefix', work, spec], { stdio: 'inherit' })

/** Decompress a .br archive and untar it into `dir/<name>`. */
const unpack = (file, name) => {
  const into = join(dir, name)
  const tar = join(dir, `${name}.tar`)
  writeFileSync(tar, brotliDecompressSync(readFileSync(file)))
  rmSync(into, { recursive: true, force: true })
  mkdirSync(into, { recursive: true })
  execFileSync('tar', ['xf', tar, '-C', into])
  rmSync(tar)
}

/** Copy every file of an unpacked archive next to the browser binary (the browser looks there). */
const flatten = from => {
  for (const entry of readdirSync(from, { withFileTypes: true })) {
    const path = join(from, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'lib') flatten(path) // shared objects sit one level down
      continue
    }
    copyFileSync(path, join(dir, entry.name))
  }
}

console.log(`headless-browser: assembling Chromium ${version} in ${dir}`)
rmSync(work, { recursive: true, force: true })
mkdirSync(work, { recursive: true })
writeFileSync(join(dir, 'README.txt'), 'Generated by scripts/headless-browser.mjs — safe to delete, never committed.\n')

// 1. The browser itself, plus its fonts and the ANGLE/SwiftShader libraries.
npm(`@sparticuz/chromium@${version}`)
const bin = join(work, 'node_modules/@sparticuz/chromium/bin')
writeFileSync(join(dir, 'chromium.bin'), brotliDecompressSync(readFileSync(join(bin, 'chromium.br'))))
chmodSync(join(dir, 'chromium.bin'), 0o755)
unpack(join(bin, 'aws.tar.br'), 'aws')
unpack(join(bin, 'swiftshader.tar.br'), 'swiftshader')

// 2. A current bundle supplies the NSS/freebl shared objects this trimmed browser misses.
npm('@sparticuz/chromium@latest')
unpack(join(work, 'node_modules/@sparticuz/chromium/bin/al2023.tar.br'), 'nss')

// 3. The Chrome 92-era SwiftShader GLES build is the one this browser actually initialises.
npm('chrome-aws-lambda@10.1.0')
unpack(join(work, 'node_modules/chrome-aws-lambda/bin/swiftshader.tar.br'), 'gles')

for (const name of ['aws', 'swiftshader', 'nss', 'gles']) flatten(join(dir, name))
// The GLES passthrough replaces the ANGLE pair shipped beside the browser.
for (const lib of ['libEGL.so', 'libGLESv2.so']) copyFileSync(join(dir, 'gles', lib), join(dir, lib))
for (const [link, target] of [['libGLESv2.so.2', 'libGLESv2.so'], ['libEGL.so.1', 'libEGL.so']]) {
  rmSync(join(dir, link), { force: true })
  symlinkSync(target, join(dir, link))
}
rmSync(work, { recursive: true, force: true })

console.log('\nheadless-browser: ready. Run the smoke test with:\n')
console.log(`  CHROMIUM_PATH="${join(dir, 'chromium.bin')}" \\`)
console.log('  CHROMIUM_ARGS="--use-gl=egl --enable-unsafe-swiftshader --no-sandbox --disable-dev-shm-usage --disable-gpu-sandbox" \\')
console.log(`  CHROMIUM_LD_LIBRARY_PATH="${dir}" \\`)
console.log('  SMOKE_TIMEOUT=1500000 corepack pnpm smoke\n')
